stages:
  - build
  - lint

build:
  stage: build
  image: golang:1.22.4
  script:
    - go mod tidy
    - go build -v ./...

lint:
  stage: lint
  image: golangci/golangci-lint:v1.59.1
  script:
    - go mod tidy
    - golangci-lint run -v
