services:
  database:
    restart: unless-stopped
    image: postgres:15
    container_name: database
    volumes:
      - ~/.pg/dishdash-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    env_file:
      - .env
    ports:
      - "1000:8080"
    depends_on:
      - database

