definitions:
  card.cardInput:
    properties:
      address:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      location:
        $ref: '#/definitions/domain.Coordinate'
      price:
        type: integer
      shortDescription:
        type: string
      tags:
        items:
          type: integer
        type: array
      title:
        type: string
    type: object
  card.cardOutput:
    properties:
      address:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      location:
        $ref: '#/definitions/domain.Coordinate'
      price:
        type: integer
      shortDescription:
        type: string
      tags:
        items:
          $ref: '#/definitions/card.tagOutput'
        type: array
      title:
        type: string
    type: object
  card.tagInput:
    properties:
      icon:
        type: string
      name:
        type: string
    type: object
  card.tagOutput:
    properties:
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  domain.Coordinate:
    properties:
      lat:
        type: number
      lon:
        type: number
    type: object
info:
  contact: {}
paths:
  /cards:
    get:
      consumes:
      - application/json
      description: Get a list of cards from the database
      produces:
      - application/json
      responses:
        "200":
          description: List of cards
          schema:
            items:
              $ref: '#/definitions/card.cardOutput'
            type: array
        "500":
          description: Internal Server Error
      summary: Get cards
      tags:
      - cards
    post:
      consumes:
      - application/json
      description: Create a new card in the database
      parameters:
      - description: Card data
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/card.cardInput'
      produces:
      - application/json
      responses:
        "200":
          description: Saved card
          schema:
            $ref: '#/definitions/card.cardOutput'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a card
      tags:
      - cards
  /cards/tags:
    post:
      consumes:
      - application/json
      description: Create a new tag in the database
      parameters:
      - description: Tag data
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/card.tagInput'
      produces:
      - application/json
      responses:
        "200":
          description: Saved tag
          schema:
            $ref: '#/definitions/card.tagOutput'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a tag
      tags:
      - cards
swagger: "2.0"
