definitions:
  dto.Card:
    properties:
      address:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      location:
        type: string
      price:
        type: integer
      short_description:
        type: string
      title:
        type: string
      type:
        $ref: '#/definitions/dto.CardType'
    type: object
  dto.CardToCreate:
    properties:
      address:
        maxLength: 255
        type: string
      description:
        type: string
      image:
        maxLength: 255
        type: string
      location:
        maxLength: 255
        type: string
      price:
        type: integer
      short_description:
        maxLength: 255
        type: string
      title:
        maxLength: 255
        minLength: 1
        type: string
      type:
        $ref: '#/definitions/dto.CardType'
    required:
    - address
    - description
    - image
    - location
    - price
    - short_description
    - title
    - type
    type: object
  dto.CardType:
    enum:
    - BAR
    - CAFE
    - RESTAURANT
    type: string
    x-enum-varnames:
    - BAR
    - CAFE
    - RESTAURANT
  dto.Lobby:
    properties:
      id:
        type: integer
      location:
        type: string
    type: object
  dto.LobbyToCreate:
    properties:
      location:
        type: string
    type: object
info:
  contact: {}
paths:
  /cards:
    get:
      consumes:
      - application/json
      description: Get a list of cards from the database
      produces:
      - application/json
      responses:
        "200":
          description: List of cards
          schema:
            items:
              $ref: '#/definitions/dto.Card'
            type: array
        "500":
          description: Internal Server Error
      summary: Get cards
      tags:
      - cards
    post:
      consumes:
      - application/json
      description: Save a new card to the database
      parameters:
      - description: Card data
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/dto.CardToCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Saved card
          schema:
            $ref: '#/definitions/dto.Card'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Save a card
      tags:
      - cards
  /lobby:
    post:
      consumes:
      - application/json
      description: Save a new lobby to the database
      parameters:
      - description: Lobby data
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/dto.LobbyToCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Saved lobby
          schema:
            $ref: '#/definitions/dto.Lobby'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Save a lobby
      tags:
      - lobby
swagger: "2.0"
